@startuml
skinparam dpi 300

class Schedule <<@Entity>> {
    + year : int
    + country : String
    {static} + findByYearAndCountry()
}

class Delivery <<@Entity>> {
    + childName : String
    + childAddress : String
    + childHasChimney : boolean
    + presentName : String
}

class SantaResource <<@Path("/api/santa")>> {
    + createASchedule(String country) : Schedule
    + getASchedule(String country, int year) : Optional<Schedule>
}

class SantaService {
    + getAllTheChildrenForASpecificCountry()
    + getEachChildAPresent()
}

SantaResource -> SantaService : "@Inject"
SantaService ..> Schedule
Schedule -left-> Delivery : "1..*"

@enduml
