@startuml
skinparam dpi 300

actor Santa

box "Santa Microservice"
participant SantaResource as santa
participant SantaService as service
participant ChildProxy as childProxy
participant PresentProxy as pokemonProxy
participant Schedule
end box

Santa -> santa : createASchedule(country)

santa -> service : getAllGoodChildren(country)
service ->X childProxy: getAllGoodChildren(country)
group @Retry @Fallback
service -> service : getLastYearSchedule()
end

santa -> service : getEachChildAPresent()
service ->X pokemonProxy: getAPresent()
group @Fallback
service -> service : getEachChildSomeLollies()
end

santa -> Schedule: persist()

@enduml
