INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1000, 'Brenna Schamberger', '10632 Damion Flat 60920-4252 Schmelermouth', false, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1001, 'Gavin O''Connell', '3790 Auer Hills 86246-3399 East Kevenmouth', false, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1002, 'Donte Deckow', '73555 Wolf Road 83923-1409 Tremblayfurt', false, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1003, 'Kelley Sporer', '489 Walter Park 49926 East Lora', true, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1004, 'Erma Willms', '8482 Beahan Walk 44602-6296 New Federicomouth', false, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1005, 'Leora Frami', '140 Woodrow Meadow 80710 Wisokyville', false, true, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1006, 'Allen Balistreri', '59892 Robert Summit 00101-8786 Port Howardville', false, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1007, 'Linsey Crona', '31809 Ebert Cape 40100 New Krystyna', true, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1008, 'Rob Kuhic', '958 Konopelski Mountains 97620 Herzogmouth', false, false, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1009, 'Cordell Bayer', '5399 Kerluke Islands 68287 North Claytonmouth', false, false, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1010, 'Chris Halvorson', '3292 Carol Bridge 12555-7963 Prohaskaborough', false, true, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1011, 'Faustino Walsh', '85287 Eli Mews 73681-8873 Ebertburgh', false, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1012, 'Calvin Blick', '61045 Bednar View 14287 MacGyverfort', false, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1013, 'Shalonda Macejkovic', '7308 Terrance Mountains 28033-5295 Sagemouth', false, true, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1014, 'Tai Steuber', '55269 Raynor Rapid 23346-8584 East Floyd', false, true, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1015, 'Fred Bosco', '2318 Chantal Stravenue 17656 North Gerry', false, false, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1016, 'Robbyn Bogisich', '3640 Tobias Cliffs 16329 Dooleyborough', true, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1017, 'Antonette Hermann', '78792 Marinda Harbors 64885-2079 Port Leochester', false, true, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1018, 'Daisy Howell', '758 Boehm Track 97210 Starkburgh', true, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1019, 'Buck Zboncak', '4442 Jenkins Manors 24737-7127 Lindsyview', false, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1020, 'Digna Runolfsson', '69270 Alfred Plains 76460-5936 North Lady', false, true, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1021, 'Wilson Mayert', '8118 Gorczany Court 25566 South Conniestad', true, true, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1022, 'Sang Dickinson', '8510 Dong Points 43779-0393 North Garry', true, false, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1023, 'Evan Hoppe', '9505 Rosenbaum Wall 48829 Lake Mark', false, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1024, 'Floyd West', '58383 Wilbur Square 65097-4168 Breitenbergfort', true, false, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1025, 'Carolee Franecki', '0289 Lavona Estate 48843 Port Ronnyfort', true, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1026, 'Mary Harvey', '8534 Pacocha Prairie 52446 South Kerri', true, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1027, 'Jefferey Blick', '12656 Conroy Views 05209-6906 North Rick', false, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1028, 'Cristin Moen', '92406 Armstrong Crossing 48164 West Marianchester', true, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1029, 'Michelina Schumm', '21152 Padberg Spur 88662-0812 New Jamelview', true, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1030, 'Jesus Bashirian', '4161 Crist Neck 07240 New Allysonport', false, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1031, 'Benny Quigley', '474 Gaylord Alley 97617-6727 Lajuanaberg', false, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1032, 'Clark Toy', '14394 Wiza Courts 18355 Saraibury', false, true, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1033, 'Collin Moen', '550 Susana Center 74256 Klingberg', false, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1034, 'Santos Sanford', '794 Rodger Causeway 58865-9985 Denesikmouth', true, true, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1035, 'Gale Leannon', '297 Tillman Rapids 55931-1220 Bergstromhaven', true, false, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1036, 'Sung Walsh', '4337 Dach Vista 52968-6337 South Lean', true, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1037, 'Glenna Strosin', '09190 Edison Mountain 51384-7040 Watsicabury', false, true, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1038, 'Pedro Murray', '43484 Eric Fall 87267 West Arletta', true, true, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1039, 'Jacquelyne Beier', '9534 Karlyn Radial 19776 East Georgetta', false, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1040, 'Merrie Parker', '098 Gleichner Ramp 26881-0196 Sanfordburgh', true, true, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1041, 'Roni Greenfelder', '7256 Courtney Ville 86162 Bentonfort', true, true, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1042, 'Annita Rempel', '11402 Smitham Shoal 01002-9713 West Geralyn', true, true, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1043, 'Janene Ortiz', '8289 Adams Canyon 71530-1247 West Brandie', false, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1044, 'Pamella Effertz', '45000 Jacobson Summit 52208-1838 Ralphmouth', false, true, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1045, 'Susann Stiedemann', '9403 Kenny Junctions 42855-9696 Odisshire', false, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1046, 'Inell Gutkowski', '140 Elvis River 38639-5384 Annalisaview', true, false, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1047, 'Madeleine Dicki', '302 Ondricka Garden 56204-0541 South Alease', true, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1048, 'Joseph Mills', '5233 Farrah Valleys 98527 Danieleborough', true, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1049, 'Harvey Langworth', '7901 Turner Mews 99981-4688 East Santiagoland', false, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1050, 'Belia Rice', '59106 Oberbrunner Fords 77009-9242 Kreigermouth', false, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1051, 'Davida Borer', '141 Jamal Ramp 09873 Germanborough', false, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1052, 'Clay Sawayn', '388 Grimes Loaf 41685 Zemlakland', true, true, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1053, 'Carole Kuphal', '3399 Maureen Lights 96971-8284 West Pricilla', false, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1054, 'Ozella Bruen', '15656 Weissnat Creek 97790-8899 Keelingtown', true, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1055, 'Raymundo Jenkins', '840 Lesch Shores 61799 Alvinbury', false, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1056, 'Damian Hayes', '3974 Elvis Union 12057 Aleishamouth', false, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1057, 'Christine Bode', '8857 Spencer Creek 95486-7615 Antoneshire', true, true, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1058, 'Nakesha Balistreri', '3886 Leffler Drive 79697-4122 Jorgestad', false, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1059, 'Quintin Fadel', '26251 Gulgowski Oval 06002 Cyrstalfort', true, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1060, 'Mayola Tromp', '428 Mauro Motorway 84341-5046 Bevville', true, true, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1061, 'Cesar Langworth', '972 Howe Highway 48249-9434 Ambrosechester', false, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1062, 'Kati Towne', '28565 Burl Creek 48709 North Benniemouth', false, true, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1063, 'Jerry Mraz', '5624 Lezlie Path 48274 East Louisa', false, false, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1064, 'Brittney Rice', '9028 Reilly Freeway 72310-2764 Danielport', true, false, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1065, 'Twyla Kulas', '43400 Reita Garden 88042-9476 South Scottyville', false, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1066, 'Wyatt Sauer', '737 Isaias Mount 47899-5951 East Angelyn', false, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1067, 'Jami Hettinger', '24373 Kozey Cliff 41551 East Angelia', true, true, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1068, 'Jennefer Parker', '807 Davis Throughway 16216-2998 Leschstad', true, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1069, 'Brendon Borer', '0978 Carita Crescent 81755 Damonmouth', true, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1070, 'Dagmar Thompson', '1661 Linn Mission 67112 Lanehaven', false, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1071, 'Ike Gutmann', '463 Bernarda Flats 36241 Huelbury', true, false, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1072, 'Bennett Hirthe', '58939 Bode Trafficway 59453 Sharitaburgh', false, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1073, 'Libbie Stiedemann', '44971 Keitha Courts 87048-6784 South Jackelineton', false, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1074, 'Leia Ward', '73098 Bert Spur 63834-2932 East Laverneport', false, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1075, 'Jeanna Mraz', '28969 Maya Fall 54385 Ikeborough', true, true, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1076, 'Tracy Schmitt', '97982 Sarai Haven 10621-0450 Port Ianfurt', false, false, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1077, 'Domonique Reilly', '42920 Rempel Run 88122 West Deidre', false, false, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1078, 'Allen Hackett', '4881 Hills Brooks 33205 Stiedemannstad', false, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1079, 'Odis Abshire', '6307 Arlie Crescent 23333-8265 South Valenciatown', false, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1080, 'Felicia Corwin', '3586 Martha Views 09188 Johnstonstad', true, true, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1081, 'Tonya Lehner', '805 Yasmin Haven 07685-5856 Johnsstad', false, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1082, 'Hedwig Dooley', '73197 Carter Mountains 94767 Moenhaven', false, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1083, 'Daisy Dach', '4849 Vandervort Ramp 17242-1974 Cronaburgh', true, true, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1084, 'Kimbery Leuschke', '01874 Daniel Place 02462-0317 Lake Skyeborough', true, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1085, 'Deetta Heathcote', '47600 Ilona Harbor 00855 South Matttown', false, true, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1086, 'Chadwick Dickinson', '969 Meta Ranch 14962 East Glady', true, true, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1087, 'Chauncey Fay', '0332 Littel Port 15813 East Frankfort', true, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1088, 'Mickey Kassulke', '815 O''Conner Glen 54044-6226 West Kierstenville', true, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1089, 'Gordon Reilly', '9717 Kunde Hill 88512 Lake Terinahaven', false, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1090, 'Johnny Zboncak', '205 Tony Valleys 45051 Schroederstad', false, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1091, 'Robin Mueller', '0184 Steuber Locks 67864-2226 Port Dorene', true, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1092, 'Shondra Rosenbaum', '3217 Cole Landing 04036-8336 Fredrickaport', false, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1093, 'Marcellus Runte', '39353 Okuneva Road 13660-5946 New Dalene', false, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1094, 'Warren Kovacek', '42879 Joel Vista 96382-8643 Feestfort', true, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1095, 'Cleora Friesen', '18736 Yon Rest 62095-8305 Earleenside', true, true, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1096, 'Lorie Hettinger', '862 Sammie Mission 57370 North Narcisa', true, true, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1097, 'Darrell Marvin', '7195 Mraz Terrace 88304 East Solfurt', true, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1098, 'Emilie Champlin', '658 Omega Rest 46151 Dwightborough', true, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1099, 'Merle Orn', '93159 Lamonica Rapids 25483-8095 East Ladonnafurt', false, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1100, 'Juanita Kuvalis', '5775 Grimes Corner 67100 Port Wallaceburgh', true, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1101, 'Danial Lehner', '1573 Brain Track 45750 South Rosalba', true, true, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1102, 'Amber Hamill', '63716 Wunsch Island 64798 Chinaburgh', true, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1103, 'Blair Rutherford', '63104 Lovie Square 66168 Susannahport', true, true, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1104, 'Pat Casper', '52514 Koch Garden 22769 New Gavin', false, false, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1105, 'Jennine Anderson', '14416 Mertz Haven 79611 Faytown', false, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1106, 'Youlanda Lowe', '153 Heidenreich Roads 35124-6463 South Williemaebury', false, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1107, 'Willie Hammes', '60335 Glenna Plaza 62268 Karanville', false, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1108, 'Darrel Bechtelar', '540 Latesha Unions 24545 Lake Ken', true, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1109, 'Rolando Conroy', '8670 Sonja Landing 76181-0543 Mertztown', false, true, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1110, 'Zada Simonis', '452 Feil View 68403-7216 Angeloton', true, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1111, 'Derek Durgan', '796 Jaskolski Garden 59812-0318 Lake Rocky', false, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1112, 'Candy Borer', '972 Syble Camp 91993 Arnoldchester', false, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1113, 'Vickie Rempel', '446 Bernhard Meadows 95581-8713 West Keenanborough', true, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1114, 'Waltraud Towne', '650 Gleason Rest 61107-1666 South Nadine', false, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1115, 'Octavio Nienow', '993 Retha Drive 59912-0457 Jackland', true, true, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1116, 'Long Cormier', '0257 Watsica Village 54702 East Rebbeca', true, true, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1117, 'Kiersten Homenick', '088 Norine Isle 93016 Brownview', true, false, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1118, 'Lelah Ruecker', '032 Thompson Mountain 56270-4621 North Michale', true, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1119, 'Clementine Hickle', '6081 David Divide 74828-5909 Haleyland', true, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1120, 'Raleigh Wisoky', '53599 Wolff Lodge 76060 West Nickiechester', false, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1121, 'Patrick Wunsch', '2156 Deangelo Estate 59271 Lake Janethmouth', true, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1122, 'Clark Goldner', '692 Marks Causeway 08296-1947 Donnellyshire', false, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1123, 'Charlesetta Hansen', '8285 Ullrich Parks 82479 Lefflerbury', true, false, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1124, 'Raleigh Green', '64799 Schroeder Meadows 92520-3398 Auerside', false, false, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1125, 'Pearly Greenholt', '503 Alejandro Coves 85367 Gulgowskiland', false, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1126, 'Thurman Borer', '3716 Janie Circles 07184-1804 Maurafurt', false, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1127, 'Carie D''Amore', '3652 Misha Land 22433 Antonyville', false, true, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1128, 'Kyle Gislason', '079 Erich Unions 44710 West Margherita', true, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1129, 'Oscar Goodwin', '9056 Crooks Courts 36718 Lake Elza', true, true, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1130, 'Gayle Morar', '192 Gislason Bypass 31735-8037 Eliciachester', false, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1131, 'Brendon Halvorson', '9763 Daysi Dale 42647-7993 Hesselshire', false, false, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1132, 'Miquel Carter', '052 Von Dam 62224-1856 Port Gregside', false, true, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1133, 'Deloras Prohaska', '5678 Fahey Common 44016-2824 New Daleview', false, true, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1134, 'Kayce Johnston', '7210 Fermin Trafficway 98838 West Pamalaburgh', true, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1135, 'Shawn Carroll', '298 Alfred Cape 63008-9052 Port Trevor', true, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1136, 'Gino Wehner', '856 Harris Turnpike 41928 Toyshire', true, true, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1137, 'Lonnie Borer', '7520 Raynor Underpass 50296-7336 Leannonstad', false, true, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1138, 'Echo Abbott', '652 Collins Street 05481 Cruzville', false, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1139, 'Ryann Bradtke', '3062 Gwyn Brook 67687 North Tristan', true, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1140, 'Karma Conroy', '69207 Cassandra Crescent 57388 Carrolltown', true, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1141, 'Derrick Reichel', '51769 Kreiger Ports 46917-1469 South Mariellechester', true, true, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1142, 'Evangelina Lowe', '987 Senger Mission 86142 West Eldora', false, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1143, 'Mandy Pfannerstill', '634 Edelmira Islands 56894 West Priscilaburgh', true, true, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1144, 'Juliann Wiegand', '79950 Cassin Ville 20601 Mendymouth', false, true, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1145, 'Tanesha Kohler', '2995 Orlando Tunnel 41653 East Judith', false, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1146, 'Douglass Hegmann', '2100 Johnson Keys 05621-0652 Strackeport', false, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1147, 'Carla Hegmann', '9325 Sheldon Cape 51509 New Philomenatown', true, false, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1148, 'Hilary Hansen', '6655 Edda Mountains 42990 North Jacob', true, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1149, 'Graciela Hoeger', '97288 Shelby Extension 11993 Creminland', true, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1150, 'Irene Marquardt', '850 Mueller Track 88188-1685 Melvinborough', true, false, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1151, 'Nobuko Kling', '45151 Hermann Landing 83024-0561 Tynishamouth', false, true, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1152, 'Arica Stamm', '445 Evan Isle 33495 Tomborough', true, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1153, 'Ellan Conroy', '5856 Andra Brook 70218 North Rhett', false, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1154, 'Johnathon Halvorson', '86180 Elanor Fields 16902-5710 New Krystina', false, false, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1155, 'Stanley Armstrong', '19614 Braun Path 87663 Kentmouth', false, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1156, 'Trudie McKenzie', '327 Anderson Route 14495-7709 Reichelland', true, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1157, 'Johnnie Von', '65173 Dalton Rue 46071 Krisstad', false, true, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1158, 'Meghann Harris', '227 Jamie Forge 21385-8053 Lake Moises', false, true, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1159, 'Buddy Daniel', '0526 Buck Center 25782 Alfonsoburgh', false, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1160, 'Ella Gleichner', '06662 Mari Burgs 18874-0690 Brekkebury', false, false, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1161, 'Alexa Schumm', '9610 Ruecker Ridge 86979-9413 Dachside', true, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1162, 'Jaime Turner', '745 Ryan Park 27923-1646 West Parismouth', false, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1163, 'Eldon Bogan', '08703 Jesse Flat 79769 Lachelleside', false, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1164, 'Shane Thiel', '318 Fernando Islands 07576 Romeostad', false, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1165, 'Ronald Muller', '927 Hirthe Pass 54946 North Jinny', false, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1166, 'Dakota Murphy', '9406 Lynch Wall 45687 North Wilburnside', true, true, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1167, 'Daisy Thiel', '7288 Batz Valley 87964 New Darrel', true, true, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1168, 'Jennette Altenwerth', '80936 Joaquin Glens 02063 New Leatricefurt', false, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1169, 'Chaya Carter', '446 Beier Square 43337-9656 Norikostad', false, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1170, 'Arnulfo Toy', '90207 Ling Prairie 42004 Andretown', true, false, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1171, 'Dylan Cremin', '998 Todd Camp 47857 Tyronestad', true, true, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1172, 'Jesus Huel', '76014 Retha Wall 38328-3418 Gingershire', true, false, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1173, 'Sammy Huels', '035 Purdy Spur 20951 Trinidadside', false, true, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1174, 'Lacey Wuckert', '07679 Garret Spur 05701 Epifaniashire', false, true, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1175, 'Janet Koepp', '189 Donetta Plains 21105 Hoegerbury', false, false, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1176, 'Antonio Langworth', '5663 Goodwin Highway 52630-6981 New Margueritamouth', false, true, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1177, 'Kristopher Cormier', '98048 Kozey Terrace 31829-2826 Edgardoland', true, true, 'Brazil');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1178, 'Ron Gerhold', '914 Angel Neck 59346 New Jakeshire', true, true, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1179, 'Caron Kshlerin', '075 McCullough Inlet 70038 Edwardport', false, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1180, 'Eli McClure', '4290 Matt Gardens 56648-5155 Boyleburgh', false, true, 'Angola');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1181, 'Boyce Connelly', '9458 Dorian Ridges 50753-4546 East Erna', false, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1182, 'Hunter Beier', '69034 Lea Camp 76287-0309 Bayerfort', true, false, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1183, 'Danyell Schaefer', '9450 Nader Via 17311 New Otisberg', false, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1184, 'Laurine Schimmel', '333 Dillon Spur 29754 West Sonberg', true, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1185, 'Faustino Nolan', '82939 Senger Key 39330-1217 West Jose', false, true, 'Argentina');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1186, 'Daren Kautzer', '898 Codi Fields 01413 Mariellaview', true, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1187, 'Lurline Konopelski', '05633 Spinka Circles 42502 Port Jenae', true, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1188, 'Jeremiah Kirlin', '55692 Tarsha Alley 67871 North Bradfordberg', true, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1189, 'Rosio Renner', '131 Curt Pines 91394-8748 East Cedricktown', false, true, 'Macau');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1190, 'Delmar MacGyver', '0014 Jaskolski Knolls 07014 Lesterport', false, false, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1191, 'Treva Barrows', '738 Gerlach Neck 55551-8436 Daughertyfurt', true, true, 'Uruguay');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1192, 'James Mante', '7871 Beer Coves 81569-1597 South Galenstad', true, false, 'Indonesia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1193, 'Michaela McDermott', '9847 Angelika Views 15282 Abernathyfort', true, false, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1194, 'Rocco Koch', '440 Skiles Fall 33540 Roxiebury', false, false, 'Malaysia');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1195, 'Joe Torp', '30715 Wisoky Divide 02137-8374 East Joliefort', true, true, 'Portugal');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1196, 'Mistie Romaguera', '4809 Savanna Alley 35436 Lorindabury', true, false, 'India');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1197, 'Joelle Will', '0843 Schumm Square 16469-7446 Muellerview', false, true, 'Venezuela');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1198, 'Tanisha Block', '511 Hubert Expressway 88532-8347 Lake Reymouth', false, true, 'Mozambique');
INSERT INTO Kid(id, name, address, chimney, naughty, country) VALUES (1199, 'Maria Treutel', '716 Gleichner Harbor 76368 North Mosheshire', false, true, 'Argentina');
