= How to Deploy a Quarkus Application to Azure with Terraform Thanks to NubesGen
Antonio Goncalves
// TOC
:toc:
:toclevels: 4

In this blog post I'll show you how to deploy a simple _Quarkus_ application to _Azure_ using _Terraform_, thanks to _NubesGen_.

== Use Case

To break it into more details, in this blog post you will learn:

* What is _Terraform_?
* What is _NubesGen_?
* Generate a basic _Quarkus_ application
* Use NubesGen to generate Terraform templates for a simple Quarkus application.
* Deploy a Quarkus application to Azure.

=== Prerequisites

== What is Terraform?

But first, let me introduce Terraform.
Terraform is...

== What is NubesGen?

There are several ways to deploy a Java application to Azure.
You can use the https://xxx[command line], the Azure Admin console https://xxx[web console], ..., or Terraform.
Terraform as several advantages, but writing the templates are a bit tricky.
That's what NubesGen is there for:
generate the Terraform templates for you.

NubesGen is an open source project that was initiated in 2021.
It lets you generate Terraform templates either using a web interface or curl commands.
For example, if you want to generate Terraform templates for a Quarkus application, you can go to https://xxx[www] and choose Quarkus from the combobox.

You can also specify the region, if the application needs a database, a Redis cache or...
This will download a zip file containing the generated templates that you can add to your project.

If, like me, you prefer the command line, NubesGen allows you to download these template throught a curl command.
Downloading throught the Web interface or the command line results in the same templates.

Let's see NubesGen in action.

== Generate a Simple Quarkus Application

First of all, let's generate a simple Quarkus application.
This application exposes a RestEndpoint that says "Hello NubesGen".
Nothing too fancy, but this allows us to focus on the deployment, not the code.

=== Bootstrap a Quarkus Application

Go to https://xxx[code.quarkus.io], specify your project name, group and artifact id, and select the Rest Easy extension.
Download the Zip file.
This is what you should have:

.Maven command to bootstrap a Quarkus application
[source,bash]
----
include::{code-github-url}/bootstrap.sh[tag=adocSnippet]
----

Now, to execute it, type `mvn quarkus:dev`.
Once Quarkus is up and ready, invoke the endpoint pointing at the URL ``.

=== Package the Application

We've just executed Quarkus in development mode.
What we need now is to package the application.
Quarkus has different ways of packaging an application:
as a Docker image, a native binary (thanks to GraalVM) or as an executable JAR.
Let's go for this option now, it's simple and portable.

To get a Uber-JAR of the application, execute the following command:

```
mvn package
```

To run the application is just a matter of executing:

```
mvn package
```

== Generate the Terraform Templates with NubesGen

We have a simple application, with no database, no authentication, nothing, packaged in an executable Uber-JAR.
Let's ask NubesGen to generate the Terraform templates.

=== Main Terraform Template

=== Application Terraform Template

== Deploy to Azure

=== Execute the Terraform Templates

=== Check the Azure Console

== Conclusion

Terraform can be tricky.
Its language is simple, but because Terraforma has an extension mecanism, its ecosystem is huge.
You can find extension for Java, for AWS, for GCP... and for Azure.
Deploying to the cloud, even a simple application, can take you a few lines of code to write.


== References

