INSERT INTO schedule (id, country, year) VALUES (2001, 'Portugal', 2019);
INSERT INTO schedule (id, country, year) VALUES (2021, 'Brazil', 2019);
INSERT INTO schedule (id, country, year) VALUES (2033, 'Angola', 2019);
INSERT INTO schedule (id, country, year) VALUES (2059, 'Mozambique', 2019);
INSERT INTO schedule (id, country, year) VALUES (2073, 'Macau', 2019);
INSERT INTO schedule (id, country, year) VALUES (2094, 'India', 2019);
INSERT INTO schedule (id, country, year) VALUES (2115, 'Malaysia', 2019);
INSERT INTO schedule (id, country, year) VALUES (2136, 'Indonesia', 2019);
INSERT INTO schedule (id, country, year) VALUES (2157, 'Venezuela', 2019);
INSERT INTO schedule (id, country, year) VALUES (2179, 'Argentina', 2019);
INSERT INTO schedule (id, country, year) VALUES (2198, 'Uruguay', 2019);

INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1002, '65450 Considine Avenue 63907 Roweshire', true, 'Kareem Hettinger', 'Machoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1003, '866 Ilda Villages 56595 Lake Emilioshire', false, 'Antione Hand', 'Bellsprout');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1004, '177 Jae Roads 88784-0019 Fisherside', false, 'Faith Cummings', 'Gyarados');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1005, '7551 Kassulke Place 87473-2089 Lake Gianna', true, 'Sacha Boyer', 'Metapod');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1006, '43569 Borer Manors 88396 Whiteberg', true, 'Alton Hackett', 'Arbok');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1007, '18278 Lesley Groves 30689 North Lezlie', true, 'Douglas Gerhold', 'Venusaur');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1008, '7803 Ziemann Keys 34585-9319 Lakinville', false, 'Kallie Ortiz', 'Farfetch''d');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1009, '27678 Antoine Tunnel 64779-7528 Shaynachester', false, 'Lillie Abshire', 'Dodrio');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1010, '542 Medhurst Points 97821 Kozeyton', false, 'Kurt Bailey', 'Psyduck');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1011, '846 Kris Club 89208 West Raeberg', false, 'Timothy Beahan', 'Dewgong');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1012, '2641 Predovic Springs 10796-9478 East Maybellehaven', false, 'Erich Feest', 'Slowpoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1013, '823 Gusikowski Rue 62422-3195 Walterberg', false, 'Trudie Kertzmann', 'Tentacool');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1014, '187 Merlin Drive 40744-7872 New Danille', false, 'Latesha Nicolas', 'Slowpoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1015, '8079 Vandervort Island 69844 Klingview', true, 'Viva Ratke', 'Slowbro');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1016, '918 Jacobs Turnpike 75099 Langfort', false, 'Dino Huel', 'Sandslash');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1017, '20845 Wes Via 81345-1928 Willianchester', true, 'Zachariah Schiller', 'Gloom');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1018, '92669 Emery Expressway 82687 Turcottemouth', true, 'Ruthanne Legros', 'Seel');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1019, '386 Thaddeus Harbor 03081 D''Amorefurt', false, 'Moises Koch', 'Moltres');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1020, '22935 Farrell Run 58981 Lennyberg', true, 'Stacey Rippin', 'Abra');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1022, '6706 Margherita Oval 43172 Port Hilary', false, 'Aracelis Bradtke', 'Dodrio');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1023, '98826 Marvin Tunnel 74196 Beckystad', true, 'Sana Oberbrunner', 'Dugtrio');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1024, '20529 Rempel Ferry 76653 New Brianneside', true, 'Cristie Schulist', 'Pidgey');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1025, '45199 Langworth Manor 71159 South Elfriede', true, 'Abraham Bartoletti', 'Mew');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1026, '37998 Ankunding Plaza 19669-5872 New Oneidaport', true, 'Lauren Senger', 'Kakuna');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1027, '765 Bernie Pass 14222 Ewaville', false, 'Pasquale Mueller', 'Alakazam');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1028, '097 Becker Shore 30365 South Emory', false, 'Waylon Koepp', 'Kadabra');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1029, '23620 Zboncak Brook 43067 West Daysi', false, 'Fredric Hudson', 'Dugtrio');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1030, '23758 Jenna Lodge 79953 Port Marianelaburgh', false, 'Eustolia Flatley', 'Kadabra');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1031, '4664 Clemencia Highway 31604-1774 Anthonybury', false, 'Alonso Anderson', 'Doduo');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1032, '390 Karin Ranch 92845 North Ramiro', true, 'Suzanna Hoppe', 'Graveler');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1034, '51407 Omar Harbor 10562 Stantonshire', false, 'Derick Hamill', 'Pidgeot');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1035, '005 Laveta Point 94657 Ornburgh', false, 'Garry Wunsch', 'Primeape');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1036, '98432 Cathern Lake 64616-3913 Hyonbury', false, 'Alissa Schulist', 'Pidgeot');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1037, '84617 Amy Station 03516 Kundefort', true, 'Arlie Greenholt', 'Venonat');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1038, '80208 Lana Locks 59276 South Luigi', true, 'Fredric Klocko', 'Fearow');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1039, '705 Bednar Throughway 23254 Port Dewittland', false, 'Angel Roob', 'Hitmonlee');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1040, '9754 Isaias View 62561 Goldnershire', true, 'Malcolm Bruen', 'Machamp');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1041, '450 Jackie Light 20481-1532 Burtstad', false, 'Tuan Crist', 'Vileplume');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1042, '2096 Hoppe Corners 08970-6491 Brakusview', true, 'Gil Brekke', 'Slowbro');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1043, '5505 Mitchell Forge 20800-5555 Colleneshire', false, 'Keisha Schmidt', 'Machoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1044, '0582 Goodwin Parkway 88489-0504 South Emileehaven', true, 'Gino Yundt', 'Paras');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1045, '527 Jacinda Mills 76695 Jacobsfort', true, 'Annmarie Hane', 'Caterpie');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1046, '362 Sipes Ways 85563-1628 Archiefurt', true, 'Manuela Weber', 'Starmie');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1047, '32262 Lubowitz Prairie 01612-1813 East Jeanice', true, 'Merrill Kuphal', 'Kangaskhan');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1048, '319 McDermott Overpass 33883 West Calvinborough', true, 'Melodie Blanda', 'Abra');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1049, '7689 Maria Villages 86013-7089 East Latina', false, 'Waneta Howe', 'Machamp');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1050, '211 Miller Bypass 48063-8639 East George', true, 'Barbar Lakin', 'Bellsprout');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1051, '0869 Delila Pass 24803 South Kelleymouth', true, 'Lamar Wiza', 'Dewgong');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1052, '96973 Bashirian Parkways 72315-3837 Stromanbury', true, 'Tad Wuckert', 'Pinsir');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1053, '4125 Terry Burg 52030-7734 West Frederic', false, 'Porsha Lubowitz', 'Bellsprout');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1054, '16264 Lubowitz Light 71093-3924 Port Rigobertoberg', true, 'Shawn McCullough', 'Parasect');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1055, '873 Marquardt Route 79964-8847 South Mario', true, 'Britt Hills', 'Dewgong');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1056, '7948 Hackett Trail 75140-8787 East Meagan', true, 'Ollie Collier', 'Pinsir');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1057, '87454 Laine Bypass 54693-1333 Lake Miloton', false, 'Blaine Oberbrunner', 'Machoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1058, '520 Moore Ferry 91459-6507 Tysonton', false, 'Bryant Beier', 'Dodrio');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1060, '802 Kunde Highway 33606-1065 McLaughlinfort', false, 'Stefan Gerlach', 'Machamp');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1061, '46616 Rocco Landing 40526-4394 Port Juttafort', false, 'Louetta Kuphal', 'Machoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1062, '8471 Nitzsche Lake 94348 North Isaura', true, 'Antwan Bahringer', 'Magmar');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1063, '881 Gleichner Plaza 87892 Gaylordstad', true, 'Lilla Gutmann', 'Rhydon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1064, '65665 Courtney Turnpike 76437 Donnybury', false, 'Enrique Hane', 'Pidgeot');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1065, '91822 Renner Ville 61922 South Sueann', true, 'Wilfredo McDermott', 'Nidoking');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1066, '503 Hyman Drive 50834-9644 North Corneliusside', false, 'Vikki Fahey', 'Pidgey');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1067, '8851 Halvorson River 16690 North Vanita', true, 'Alona Tromp', 'Sandslash');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1068, '9475 Gwenda Shoal 95421 South Stephan', false, 'Gavin Dach', 'Machoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1069, '9014 Barton Estates 22727-4343 Allenaville', false, 'Krysten Kihn', 'Paras');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1070, '578 Rice Haven 85091-0937 Roobville', false, 'Jospeh Torp', 'Omastar');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1071, '23048 Marilyn Bridge 70086-9319 Prohaskashire', false, 'Kira Krajcik', 'Gyarados');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1072, '446 Corwin Gateway 10197-0425 Zemlakborough', false, 'Cristal Rath', 'Kangaskhan');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1074, '068 Feil Wells 97544 Kathleenhaven', true, 'Raymond Jenkins', 'Sandslash');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1075, '532 Cris Trail 64721 Barryborough', false, 'Quentin Hyatt', 'Pikachu');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1076, '351 Buckridge Fall 77672-2055 Lake Ozell', false, 'Angelita Medhurst', 'Dewgong');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1077, '59135 Vandervort Burgs 30817 East Darellchester', false, 'Burt Simonis', 'Voltorb');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1078, '4988 Clelia Springs 09096 Moisesside', true, 'Joel Wilkinson', 'Kangaskhan');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1079, '033 Rick Pike 23380 Port Brent', true, 'Devon Sanford', 'Starmie');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1080, '677 Pagac Forks 98465-4761 Port Bentonstad', false, 'Malcom Prosacco', 'Parasect');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1081, '58943 Nathaniel Pines 61153 East Harris', true, 'Jamaal Goyette', 'Machoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1082, '792 Kirlin Forges 82453-0554 West Noeliaport', true, 'Danial Keeling', 'Mewtwo');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1083, '55112 Clyde Court 09581-3325 Sandymouth', false, 'Josette Hyatt', 'Marowak');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1084, '10267 Kary Lodge 64228 New Ahmadton', true, 'Chas Olson', 'Nidoran');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1085, '7155 Renda Summit 41124-9658 Francischester', true, 'Mervin Johns', 'Metapod');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1086, '898 Orville Meadows 03415-4581 Cronastad', true, 'Kristopher Wiegand', 'Rhydon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1087, '4257 Arlen Meadows 34669-8499 Ornborough', false, 'Hildegard Klocko', 'Machoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1088, '7371 Nestor Mountain 88181-3377 North Vicenteberg', true, 'Ira Quigley', 'Tentacool');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1089, '397 Lowe Stream 74684-2213 East Beau', true, 'Abbie Wilderman', 'Bellsprout');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1090, '27054 Jame Grove 13707 Kemmerfurt', false, 'Cruz Rath', 'Parasect');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1091, '1208 Therese Forge 07912-3928 Port Brandyview', false, 'Emery Walter', 'Gyarados');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1092, '361 Mills Falls 56164-0461 West Tommieland', false, 'Raymon Kessler', 'Mew');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1093, '9289 Andres Common 87906-3532 Leuschkeborough', false, 'Vita Kertzmann', 'Metapod');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1095, '23065 Winfred Expressway 26972-2099 Bergefort', false, 'Clair Ryan', 'Kangaskhan');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1096, '888 Beatrice Throughway 89849 Christeenland', true, 'Deandre Kiehn', 'Hitmonlee');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1097, '92655 Metz Inlet 04162-1123 North Dalenebury', true, 'Donovan Sipes', 'Graveler');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1098, '4076 Leland Route 50270 Kuphalfort', true, 'Lacie Kris', 'Pinsir');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1099, '3557 Ankunding Square 84382 Aufderharview', false, 'Almeda Casper', 'Exeggcute');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1100, '040 Schulist Course 86536 South Lawanna', true, 'Randall Schulist', 'Vileplume');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1101, '5778 Neda Well 29447-5880 Christiansenfort', true, 'Tori Gerlach', 'Gloom');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1102, '7702 Andre Radial 07673 Port Jettie', true, 'Keely Dach', 'Sandslash');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1103, '2327 Gutkowski Island 57369 South Salvador', true, 'Earnest Tromp', 'Tentacool');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1104, '63643 Edgardo View 35023 East Gerardview', true, 'Huey Fahey', 'Fearow');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1105, '4880 Bernard Lane 37831 East Levitown', true, 'Latonya Kshlerin', 'Caterpie');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1106, '951 Padberg Prairie 08137-8440 Freddiemouth', false, 'Angelena Weber', 'Slowbro');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1107, '8068 Brendon Prairie 93242 Port Teresa', false, 'Bulah Lowe', 'Tentacruel');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1108, '46307 Rempel Radial 07240-2175 Colestad', false, 'Cher Bednar', 'Zubat');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1109, '593 Feest Ridge 72065-3569 Lavonnetown', false, 'Nita Ortiz', 'Gloom');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1110, '11234 Gil Park 84909-5618 Haagmouth', false, 'Erminia Legros', 'Staryu');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1111, '75760 Annalee Ways 27336 East Ignaciofurt', true, 'Arnoldo Frami', 'Jolteon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1112, '6829 Elaina Track 90501 Crissyport', true, 'Felipe Krajcik', 'Zubat');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1113, '84029 Boyer Freeway 26329 Rickyland', false, 'Kendrick Metz', 'Kadabra');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1114, '011 Greenholt Place 29288 Corrinfurt', false, 'Tama Runte', 'Psyduck');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1116, '5124 Bonita Plains 07834-2427 Conroyshire', true, 'Norris Gleichner', 'Zubat');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1117, '3254 Aron Union 60197 South Domenicaview', true, 'Cameron Reinger', 'Beedrill');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1118, '6571 Ernesto Square 79462 Danicaville', false, 'Ned Murray', 'Doduo');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1119, '8586 Kathaleen Inlet 70946 West Thao', false, 'Clemente Effertz', 'Kangaskhan');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1120, '34913 Preston Canyon 23192-2263 East Sebastian', true, 'Art O''Kon', 'Abra');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1121, '134 Bruen Roads 11540-7949 Duncanberg', false, 'Johnathon Corkery', 'Moltres');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1122, '10971 Carroll Valleys 57376-0826 Bradleyberg', false, 'Lenore Swaniawski', 'Kabutops');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1123, '451 Bergnaum Squares 05993 North Geraldochester', false, 'Adalberto Mohr', 'Gloom');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1124, '7600 Hauck Stravenue 72054-8840 West Stevie', false, 'Son Botsford', 'Dodrio');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1125, '14309 Vaughn Hills 45435-2664 North Dora', false, 'Val Bernhard', 'Gengar');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1126, '9664 George Ville 74024-8262 Port Lylehaven', false, 'Pamela O''Conner', 'Jolteon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1127, '9255 Nicky River 78073-1976 Alleneton', true, 'Nigel Satterfield', 'Tauros');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1128, '600 Tish Brook 64855 South Roryburgh', false, 'Charis Reinger', 'Kabutops');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1129, '015 Frami Spurs 73332-5436 West Guadalupeview', false, 'Wayne Nikolaus', 'Vileplume');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1130, '61875 Walker Trafficway 74875-8645 West Tyler', false, 'Jackie Steuber', 'Zubat');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1131, '69675 Fay Corners 06937 North Marilynhaven', true, 'Thad Ratke', 'Tentacruel');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1132, '8956 Runolfsson Run 45685-1204 East Hoytland', true, 'Young Koch', 'Pinsir');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1133, '62582 Danny Bridge 13969-7841 Wolffbury', false, 'Mohammad Davis', 'Gyarados');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1134, '359 Maisie Canyon 09299 Port Suzan', true, 'Kristopher Rohan', 'Magmar');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1135, '967 Jordon Field 49314-5978 South Ahmed', true, 'Darrell Champlin', 'Pidgeotto');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1137, '776 Hartmann Locks 48007-6618 East Rubi', true, 'Elbert Schmeler', 'Pinsir');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1138, '5299 Hilario Well 60351-1919 East Gilberthaven', false, 'Craig Wunsch', 'Rhydon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1139, '9102 Orlando Station 21735 Cassintown', true, 'Taunya Grant', 'Parasect');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1140, '719 Wolff Landing 98741 Wolffhaven', false, 'Brock Predovic', 'Pidgey');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1141, '6613 Nicolas Knoll 86452-6785 Lueilwitztown', true, 'Lady Schumm', 'Machamp');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1142, '45303 Susannah Meadow 55658 North Alejandro', true, 'Nanci Schumm', 'Metapod');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1143, '818 Fransisca Vista 98583-8480 Fumikomouth', false, 'Julian Bechtelar', 'Jolteon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1144, '166 Seymour Manor 89125-4850 Annastad', false, 'Deane Morar', 'Caterpie');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1145, '0861 Nena Village 60054 West Martin', true, 'Bernita Mraz', 'Machoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1146, '21038 Ty Harbor 50295-5134 Laurenmouth', false, 'Ginette Medhurst', 'Dodrio');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1147, '2333 Ernesto Ville 21400 West Romaville', true, 'Olivia McGlynn', 'Dragonair');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1148, '4561 Emerson Meadow 49919-3036 Mohrmouth', true, 'Delmer Stehr', 'Metapod');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1149, '33025 Ciara Rue 91279-7934 North Margebury', true, 'Kenna Mayert', 'Marowak');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1150, '875 Mardell Knolls 33773-5723 North Emilio', true, 'Jovan Adams', 'Rhydon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1151, '2668 Pacocha Causeway 95348-0871 Deckowborough', true, 'Jeanna Ernser', 'Doduo');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1152, '417 Shirly Trafficway 09839-7810 Bogisichport', false, 'Michaela Adams', 'Jolteon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1153, '11459 Noe Haven 99941 Hahnshire', true, 'Karol Rolfson', 'Mankey');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1154, '450 Feeney Junction 64545-1170 Janayton', true, 'Mindy Lynch', 'Voltorb');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1155, '1479 Lynch Land 30279-0203 O''Connellfurt', true, 'Ariel Stroman', 'Parasect');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1156, '0479 Shayna Lodge 71444 Port Aminaport', true, 'Tomeka Heathcote', 'Venonat');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1158, '029 Schroeder Lodge 27200 North Tameika', false, 'Shonta Lowe', 'Mew');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1159, '6365 Lemke Meadow 75084 Lake Peter', true, 'Santo Roberts', 'Marowak');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1160, '86068 Boyer Glens 80760-7728 Hermistonview', true, 'Garret Cummerata', 'Venonat');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1161, '1964 Bauch Burgs 15325-1662 West Shelley', false, 'China Mante', 'Hitmonlee');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1162, '8775 Veola Corners 53091 Larsonmouth', true, 'Alejandro Gislason', 'Machamp');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1163, '88138 Dickinson Islands 39306-9822 Lake Mireyastad', false, 'Timothy Crooks', 'Exeggcute');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1164, '058 Auer Stravenue 17202-6600 North Margotstad', false, 'Kenton Bruen', 'Pikachu');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1165, '719 Douglas Rest 87250 Nedhaven', true, 'Joshua Roberts', 'Jolteon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1166, '6042 Merideth Point 97592 South Keikostad', true, 'Mitchel Okuneva', 'Eevee');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1167, '47924 Braun Shore 88248 West Sibyl', false, 'Buena Wiegand', 'Rhydon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1168, '6539 Little Union 11440-5815 Arronshire', false, 'Carroll Legros', 'Gloom');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1169, '7170 Pricilla Square 70983 New Deanbury', true, 'Maryland Kohler', 'Nidoran');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1170, '644 Janella Inlet 15321-3065 Lake Cassondraville', false, 'Fredrick Funk', 'Sandslash');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1171, '3612 Adrian Ridge 84060-1503 Lake Nicolastad', false, 'Dion Rutherford', 'Jolteon');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1172, '53005 Champlin Greens 18527-7524 Hansview', false, 'Jaimie Feil', 'Fearow');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1173, '11822 Luann Locks 93581-7996 New Eltonhaven', true, 'Josue O''Kon', 'Hitmonlee');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1174, '263 Bethany Junction 94280 Carltonhaven', true, 'Dania Heaney', 'Metapod');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1175, '732 Efrain Harbors 37907-9670 Bodeshire', true, 'Alexander Collier', 'Zubat');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1176, '8962 Upton Stream 13638-6214 West Woodrowshire', false, 'Loria Hudson', 'Primeape');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1177, '76092 Marlon Pine 80509 Nicolaschester', false, 'Thalia Osinski', 'Zubat');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1178, '9640 Ziemann Circles 37779 South Alphonse', false, 'Guadalupe Schulist', 'Eevee');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1180, '6177 Schamberger Club 88147-4429 West Latashahaven', false, 'Soo Metz', 'Caterpie');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1181, '75831 Tenesha Parks 60214 Port Cliffordland', false, 'Dania Waelchi', 'Gyarados');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1182, '843 O''Keefe Viaduct 23057 South Ozzie', false, 'Cameron Osinski', 'Magmar');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1183, '63768 Fay Prairie 59314-4579 New Monteberg', false, 'Sage DuBuque', 'Caterpie');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1184, '400 Medhurst Locks 64822 Paolashire', true, 'Suellen Mayer', 'Dodrio');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1185, '061 Reynolds Estates 44891-7471 Auerville', true, 'Reggie Brakus', 'Paras');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1186, '138 Lindgren Flats 33231-5252 Rosenbaumshire', false, 'Thaddeus Greenfelder', 'Moltres');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1187, '3604 Yundt Valleys 81726-6273 Hirthehaven', false, 'Rudolf Cummings', 'Voltorb');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1188, '71741 Jerde Springs 67071-8081 Peggyberg', true, 'Lorenza Bartoletti', 'Voltorb');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1189, '958 Labadie Plains 55006 Lake Caylaborough', true, 'Ta Cummings', 'Doduo');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1190, '3180 Bechtelar Views 31001 Yelenaside', true, 'Aurea Vandervort', 'Metapod');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1191, '605 Nienow Springs 75522 Unside', true, 'Dionne Rutherford', 'Magmar');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1192, '7124 Brendan Forest 88197-2651 West Akilah', false, 'Arthur Prosacco', 'Pikachu');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1193, '64995 Jean Prairie 05038-7962 New Sammy', false, 'Luciano Rodriguez', 'Graveler');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1194, '659 Emil Ramp 00009-3479 New Wademouth', false, 'Quinn Abshire', 'Cubone');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1195, '799 Nienow Plaza 21139-2126 North Sadyehaven', true, 'Jamel Sanford', 'Slowbro');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1196, '3212 Blanda Parkways 44544 Hoegermouth', true, 'Dorinda Ritchie', 'Kabutops');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1197, '7983 Bergstrom Loop 78039-3537 Neilmouth', false, 'Lisa Haley', 'Staryu');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1199, '541 Weber Oval 51379 South Noelburgh', false, 'Oswaldo McLaughlin', 'Slowpoke');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1200, '854 Hilll Court 41612-7948 Runolfsdottirhaven', false, 'Maryam Ondricka', 'Bellsprout');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1201, '29109 Homenick Hollow 90199 Lefflerfort', false, 'Dillon Toy', 'Pidgeotto');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1202, '55306 McLaughlin Skyway 69056-4936 Haitown', false, 'Cedrick Kunde', 'Kadabra');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1203, '1119 Collins Shoals 09366 East Eric', true, 'Jc Conroy', 'Staryu');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1204, '5728 Bartoletti Unions 76335 Dinafort', true, 'Kevin Tremblay', 'Kangaskhan');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1205, '2091 Clark Oval 31979-1405 Lake Abrahammouth', true, 'Donnie Brown', 'Dragonair');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1206, '021 Schuppe Ville 82653-0749 New Von', false, 'Willian Abshire', 'Rhyhorn');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1207, '280 Jacobson Points 92640-6793 West Apolonia', true, 'Shirley O''Reilly', 'Voltorb');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1208, '3197 Eddy Rue 41843-4026 Mervinville', false, 'Carole Pouros', 'Staryu');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1209, '0756 Nader Extension 71329-5134 West Arnulfomouth', false, 'Shanda Kunze', 'Hitmonlee');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1210, '9138 Timmy Creek 38266 Lorileeborough', false, 'Zachary Senger', 'Dewgong');
INSERT INTO delivery (id, childaddress, childhaschimney, childname, presentname) VALUES (1211, '095 Dwain Ridges 57656-6036 Robertsmouth', false, 'Azzie Tremblay', 'Pidgey');

INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1002);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1003);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1004);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1005);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1006);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1007);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1008);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1009);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1010);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1011);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1012);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1013);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1014);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1015);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1016);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1017);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1018);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1019);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2001, 1020);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1022);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1023);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1024);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1025);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1026);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1027);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1028);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1029);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1030);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1031);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2021, 1032);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1034);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1035);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1036);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1037);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1038);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1039);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1040);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1041);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1042);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1043);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1044);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1045);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1046);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1047);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1048);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1049);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1050);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1051);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1052);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1053);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1054);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1055);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1056);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1057);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2033, 1058);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1060);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1061);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1062);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1063);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1064);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1065);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1066);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1067);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1068);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1069);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1070);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1071);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2059, 1072);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1074);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1075);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1076);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1077);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1078);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1079);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1080);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1081);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1082);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1083);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1084);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1085);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1086);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1087);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1088);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1089);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1090);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1091);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1092);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2073, 1093);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1095);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1096);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1097);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1098);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1099);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1100);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1101);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1102);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1103);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1104);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1105);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1106);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1107);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1108);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1109);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1110);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1111);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1112);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1113);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2094, 1114);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1116);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1117);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1118);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1119);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1120);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1121);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1122);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1123);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1124);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1125);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1126);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1127);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1128);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1129);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1130);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1131);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1132);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1133);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1134);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2115, 1135);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1137);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1138);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1139);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1140);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1141);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1142);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1143);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1144);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1145);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1146);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1147);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1148);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1149);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1150);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1151);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1152);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1153);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1154);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1155);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2136, 1156);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1158);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1159);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1160);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1161);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1162);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1163);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1164);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1165);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1166);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1167);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1168);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1169);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1170);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1171);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1172);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1173);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1174);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1175);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1176);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1177);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2157, 1178);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1180);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1181);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1182);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1183);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1184);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1185);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1186);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1187);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1188);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1189);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1190);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1191);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1192);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1193);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1194);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1195);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1196);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2179, 1197);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1199);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1200);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1201);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1202);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1203);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1204);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1205);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1206);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1207);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1208);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1209);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1210);
INSERT INTO schedule_delivery (schedule_id, deliveries_id) VALUES (2198, 1211);
