@startuml
!include style.iuml
allow_mixing
left to right direction

rectangle "Terraform Core" as core {
}

rectangle "Providers" as provider {
  rectangle "AWS" as aws {
  }
  rectangle "GCP" as gcp {
  }
  rectangle "Azure" as azure {
  }
  rectangle "..." as etc {
  }
}

aws -[hidden]r-> gcp
gcp -[hidden]d-> azure
azure -[hidden]l-> etc
etc -[hidden]u-> aws

core --> provider

@enduml
