@startuml
!include style.iuml
allow_mixing
left to right direction

rectangle Cloud {
  cloud Azure {
  }
}

rectangle Development {
  package UberJAR {
    class GreetingResource {
      + @GET hello(): String
    }
  }
  artifact "Terraform\nFiles" as Terraform
}

Terraform -[hidden]-> GreetingResource
GreetingResource ..> Cloud : "Deployment\nAzure Maven plugin"

@enduml
