skinparam dpi 300

skinparam BackgroundColor transparent
skinparam DefaultFontColor #262626
skinparam DefaultFontSize 20

skinparam CircledCharacterFontColor #262626

skinparam Class {
  ArrowColor #262626
  BackgroundColor #ECECED
  BorderColor #262626
  HeaderBackgroundColor #747F83
  FontColor #F2F2F2
  StereotypeFontColor #F2F2F2
}

skinparam Artifact {
  BackgroundColor #ECECED
  BorderColor #262626
  FontColor #747F83
  StereotypeFontColor #B6AF9D
}

skinparam State {
  AttributeFontColor #F2F2F2
  BackgroundColor #747F83
  BorderColor #262626
  EndColor #B6AF9D
  FontColor #F2F2F2
  StartColor #B6AF9D
}

skinparam Activity {
  AttributeFontColor #F2F2F2
  BackgroundColor #747F83
  BorderColor #262626
  FontColor #F2F2F2
}

skinparam Icon {
  PublicBackgroundColor #ACD0CA
  PublicColor #ACD0CA
  PrivateBackgroundColor #ACD0C0
  PrivateColor #ACD0C0
}

skinparam StereotypeABackgroundColor #B6AF9D
skinparam StereotypeCBackgroundColor #B6AF9D
skinparam StereotypeIBackgroundColor #D6CEB5
