INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1000, 'Venusaur', 'Runte-Flatley', 553);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1001, 'Abra', 'Bernier-Veum', 675);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1002, 'Marowak', 'Price Group', 893);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1003, 'Dodrio', 'Block-Wiza', 620);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1004, 'Gyarados', 'DuBuque Group', 223);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1005, 'Bellsprout', 'Littel, Raynor and Dickinson', 966);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1006, 'Paras', 'Dooley LLC', 583);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1007, 'Dragonair', 'Rolfson, Hilll and Heidenreich', 920);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1008, 'Machoke', 'Farrell-Bogisich', 414);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1009, 'Venonat', 'Erdman Inc', 274);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1010, 'Bellsprout', 'Gleason LLC', 699);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1011, 'Zubat', 'Welch Inc', 915);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1012, 'Machamp', 'Prohaska, Becker and Dicki', 303);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1013, 'Slowbro', 'Lakin, Rath and Okuneva', 877);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1014, 'Ivysaur', 'Mueller, Blanda and Dach', 160);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1015, 'Beedrill', 'Moen, Dach and Deckow', 532);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1016, 'Eevee', 'Willms, Reichert and Johnson', 720);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1017, 'Dodrio', 'Streich, Christiansen and Bashirian', 750);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1018, 'Primeape', 'Schaden Group', 475);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1019, 'Pidgeotto', 'Zboncak, Brakus and Borer', 401);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1020, 'Seel', 'Lueilwitz, Zemlak and Crist', 593);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1021, 'Hitmonlee', 'Pacocha Inc', 337);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1022, 'Jolteon', 'Harvey Group', 787);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1023, 'Kabutops', 'Kutch, Beatty and Jaskolski', 396);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1024, 'Machoke', 'Satterfield and Sons', 63);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1025, 'Graveler', 'Swaniawski LLC', 736);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1026, 'Slowbro', 'Crist, Marks and Howell', 731);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1027, 'Dugtrio', 'Hessel Inc', 143);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1028, 'Paras', 'Ullrich, Vandervort and Jerde', 780);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1029, 'Pidgeot', 'Roob Group', 569);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1030, 'Cubone', 'Zieme, Batz and Nikolaus', 34);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1031, 'Kangaskhan', 'Oberbrunner, Mohr and Bednar', 753);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1032, 'Kabutops', 'Schiller LLC', 423);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1033, 'Pinsir', 'Grady-Herzog', 931);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1034, 'Pikachu', 'Blick and Sons', 61);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1035, 'Gyarados', 'Hilpert Group', 293);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1036, 'Vileplume', 'Murazik Inc', 620);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1037, 'Tentacool', 'Schulist, Halvorson and Dickinson', 218);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1038, 'Fearow', 'Schmeler LLC', 847);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1039, 'Psyduck', 'Gutmann-Mueller', 537);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1040, 'Zubat', 'Hayes, Berge and Hand', 919);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1041, 'Pinsir', 'Wisoky, Marks and Johnson', 716);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1042, 'Beedrill', 'Hilll and Sons', 544);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1043, 'Hitmonlee', 'Nienow Group', 746);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1044, 'Doduo', 'Bartell, Krajcik and Kemmer', 713);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1045, 'Omastar', 'Turner-McKenzie', 452);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1046, 'Magmar', 'Smitham, Hayes and Yost', 520);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1047, 'Venomoth', 'Klein Inc', 230);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1048, 'Vileplume', 'Mann-Monahan', 461);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1049, 'Beedrill', 'Morar, Maggio and Cruickshank', 671);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1050, 'Dewgong', 'Lindgren LLC', 361);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1051, 'Mankey', 'Paucek Group', 484);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1052, 'Kadabra', 'Kovacek, Krajcik and Wuckert', 186);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1053, 'Arbok', 'Borer and Sons', 598);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1054, 'Kangaskhan', 'Stokes Inc', 531);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1055, 'Dodrio', 'Haag-MacGyver', 275);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1056, 'Sandslash', 'Heidenreich-Hills', 551);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1057, 'Caterpie', 'Bashirian-Crona', 358);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1058, 'Pidgey', 'Shanahan, Baumbach and Lockman', 680);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1059, 'Nidoking', 'Boyle-Skiles', 923);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1060, 'Starmie', 'Pfeffer-Donnelly', 129);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1061, 'Jolteon', 'Kshlerin LLC', 810);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1062, 'Gengar', 'Gleichner, Welch and MacGyver', 91);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1063, 'Zubat', 'Goodwin-Welch', 375);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1064, 'Venonat', 'Torp, Mertz and West', 615);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1065, 'Rhydon', 'Towne, Hessel and Konopelski', 111);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1066, 'Rhydon', 'Ryan-Medhurst', 171);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1067, 'Gengar', 'Shanahan, Schulist and Walter', 372);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1068, 'Gloom', 'Osinski, Metz and Becker', 947);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1069, 'Nidoran', 'Kling, Prohaska and Koss', 584);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1070, 'Hitmonlee', 'Streich-Kohler', 624);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1071, 'Parasect', 'Deckow, Anderson and Hickle', 594);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1072, 'Kakuna', 'Bednar and Sons', 129);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1073, 'Machamp', 'Rath, Wunsch and Hand', 305);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1074, 'Pidgey', 'Zboncak, Doyle and Jacobs', 62);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1075, 'Caterpie', 'Blick LLC', 494);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1076, 'Graveler', 'Marvin, McGlynn and Hackett', 603);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1077, 'Voltorb', 'McGlynn-Langworth', 887);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1078, 'Metapod', 'Conn, Wintheiser and Mayert', 689);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1079, 'Rhyhorn', 'Mann, Cassin and Littel', 537);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1080, 'Mewtwo', 'Jacobson, Senger and Bauch', 409);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1081, 'Tauros', 'Skiles-Russel', 602);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1082, 'Metapod', 'Schinner, Jaskolski and Rolfson', 754);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1083, 'Pidgeot', 'Hilpert Inc', 591);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1084, 'Gyarados', 'Larkin Inc', 350);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1085, 'Alakazam', 'Wilderman, Langworth and Funk', 614);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1086, 'Tentacruel', 'Kessler-MacGyver', 507);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1087, 'Horsea', 'Hackett, Ortiz and Conn', 825);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1088, 'Moltres', 'Smith Inc', 323);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1089, 'Farfetch''d', 'Grimes and Sons', 871);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1090, 'Mew', 'Conn and Sons', 313);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1091, 'Mr. Mime', 'McGlynn LLC', 517);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1092, 'Kadabra', 'Ankunding, Reilly and Bosco', 604);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1093, 'Goldeen', 'Funk-Bernhard', 276);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1094, 'Slowpoke', 'Bradtke LLC', 147);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1095, 'Machoke', 'White Group', 205);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1096, 'Exeggcute', 'King Group', 574);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1097, 'Nidoran', 'Hirthe and Sons', 423);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1098, 'Kadabra', 'Kuphal-Mohr', 623);
INSERT INTO Pokemon(id, name, manufacturer, weight) VALUES (1099, 'Staryu', 'Pfeffer, Dicki and Auer', 753);
