INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1000, 'Eevee', 'Keeling, Waters and Hammes', 561);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1001, 'Drowzee', 'Conn-Renner', 294);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1002, 'Mew', 'Sporer LLC', 626);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1003, 'Mankey', 'Terry, Bradtke and Kutch', 129);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1004, 'Oddish', 'Howell-Feeney', 18);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1005, 'Drowzee', 'Littel-Wisozk', 614);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1006, 'Kadabra', 'Cartwright Group', 153);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1007, 'Rhyhorn', 'O''Connell, Schuppe and Botsford', 229);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1008, 'Machamp', 'Gusikowski-Adams', 178);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1009, 'Chansey', 'Fadel and Sons', 385);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1010, 'Rapidash', 'Kozey, Toy and Adams', 308);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1011, 'Mr. Mime', 'Hills Group', 464);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1012, 'Shellder', 'Nitzsche, Swift and Daniel', 343);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1013, 'Venusaur', 'Bahringer, Hane and Muller', 238);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1014, 'Vaporeon', 'Rodriguez Group', 135);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1015, 'Goldeen', 'Wyman, Kautzer and D''Amore', 238);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1016, 'Dewgong', 'Blanda-Mueller', 737);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1017, 'Dugtrio', 'Schuppe, Turner and Rosenbaum', 716);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1018, 'Haunter', 'Emmerich, Cremin and Schulist', 476);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1019, 'Ditto', 'Zieme, Pagac and Weissnat', 596);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1020, 'Abra', 'Kertzmann LLC', 251);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1021, 'Rapidash', 'Williamson and Sons', 825);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1022, 'Dragonair', 'Brekke, Bogisich and Feeney', 488);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1023, 'Poliwag', 'Bradtke, Ferry and Gutmann', 934);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1024, 'Charmander', 'Hoeger, Mraz and Langworth', 442);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1025, 'Haunter', 'Stark, Murray and Wilderman', 380);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1026, 'Koffing', 'Douglas Group', 849);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1027, 'Seel', 'Spinka Inc', 418);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1028, 'Magmar', 'Pollich, O''Keefe and Beier', 185);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1029, 'Raichu', 'Koss Inc', 101);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1030, 'Mr. Mime', 'Kuhlman, Goyette and Goodwin', 185);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1031, 'Dragonair', 'Zemlak, Gislason and Thiel', 381);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1032, 'Mankey', 'Lueilwitz-Purdy', 414);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1033, 'Jigglypuff', 'Keeling and Sons', 819);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1034, 'Sandshrew', 'Botsford, Gutmann and O''Connell', 654);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1035, 'Starmie', 'Kozey, Bogan and McDermott', 616);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1036, 'Tangela', 'Bruen LLC', 169);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1037, 'Poliwhirl', 'Rolfson Group', 55);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1038, 'Victreebel', 'King-Hansen', 768);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1039, 'Pidgeotto', 'Braun and Sons', 500);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1040, 'Seel', 'Morar-Kohler', 214);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1041, 'Ditto', 'McCullough and Sons', 944);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1042, 'Farfetch''d', 'Bernier and Sons', 900);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1043, 'Seadra', 'Parisian LLC', 979);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1044, 'Rhyhorn', 'Pagac-Ullrich', 830);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1045, 'Mr. Mime', 'Conn and Sons', 125);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1046, 'Weepinbell', 'Donnelly-Rice', 185);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1047, 'Jolteon', 'Mraz, Hand and Russel', 592);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1048, 'Dodrio', 'Dibbert, Kshlerin and Kunze', 701);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1049, 'Charmeleon', 'Dietrich, D''Amore and Gerlach', 357);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1050, 'Jigglypuff', 'Ankunding Inc', 557);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1051, 'Paras', 'Pouros, O''Hara and Skiles', 715);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1052, 'Tentacruel', 'Homenick, Bradtke and Boyer', 409);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1053, 'Staryu', 'Hegmann, Monahan and Bartoletti', 890);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1054, 'Gloom', 'Mitchell LLC', 644);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1055, 'Seel', 'Ziemann and Sons', 574);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1056, 'Arcanine', 'Welch Inc', 627);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1057, 'Charizard', 'Keeling, Kautzer and Jerde', 663);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1058, 'Goldeen', 'Langosh LLC', 734);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1059, 'Koffing', 'Treutel Inc', 939);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1060, 'Magnemite', 'Cummings Inc', 464);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1061, 'Primeape', 'Ward-Nienow', 814);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1062, 'Ditto', 'Lehner-Smith', 573);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1063, 'Tentacool', 'Pfeffer, Cole and Donnelly', 134);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1064, 'Marowak', 'Kiehn Group', 291);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1065, 'Horsea', 'Klein-O''Reilly', 223);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1066, 'Magnemite', 'Moen, Kuhic and Dickens', 52);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1067, 'Seaking', 'McGlynn, Bernier and Sipes', 832);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1068, 'Gastly', 'Jacobs, Hills and Robel', 546);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1069, 'Slowpoke', 'Kozey, Dickinson and Bergstrom', 358);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1070, 'Exeggcute', 'Schimmel, Heathcote and Halvorson', 380);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1071, 'Alakazam', 'DuBuque-Barton', 889);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1072, 'Rattata', 'Harris Group', 635);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1073, 'Abra', 'Donnelly-Boehm', 779);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1074, 'Growlithe', 'Hintz-Leffler', 383);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1075, 'Machamp', 'Murphy-Nienow', 947);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1076, 'Porygon', 'Hettinger, Hessel and Rutherford', 158);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1077, 'Kabuto', 'Miller, Goldner and Yundt', 46);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1078, 'Raichu', 'Hettinger LLC', 652);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1079, 'Pinsir', 'Metz-Powlowski', 264);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1080, 'Mr. Mime', 'Green-Reinger', 911);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1081, 'Vulpix', 'Fahey, Bode and Bednar', 439);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1082, 'Graveler', 'Sporer, Glover and Hauck', 367);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1083, 'Poliwrath', 'Kihn, Gleason and Reilly', 165);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1084, 'Dodrio', 'Kuhic, Cartwright and Kirlin', 665);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1085, 'Parasect', 'Nader Group', 488);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1086, 'Arcanine', 'Hoppe, Dicki and Purdy', 355);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1087, 'Lapras', 'Barton-Smith', 824);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1088, 'Wigglytuff', 'Sawayn-Hahn', 647);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1089, 'Squirtle', 'VonRueden Group', 251);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1090, 'Poliwag', 'Kris-Volkman', 479);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1091, 'Victreebel', 'Runte, Langworth and Wiza', 25);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1092, 'Rhydon', 'Kulas, Price and Ruecker', 379);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1093, 'Snorlax', 'Erdman, DuBuque and Hirthe', 292);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1094, 'Tangela', 'Cole, Koss and Weimann', 810);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1095, 'Rapidash', 'Marks-Kris', 655);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1096, 'Ponyta', 'Brekke-Lebsack', 908);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1097, 'Sandslash', 'Considine, Lindgren and Kemmer', 899);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1098, 'Lapras', 'Weber-White', 319);
INSERT INTO Toy(id, name, manufacturer, weight) VALUES (1099, 'Dragonair', 'Hand Inc', 953);
