= How to Deploy a Quarkus Application to Azure with GitHub Actions Thanks to NubesGen
Antonio Goncalves
// TOC
:toc:
:toclevels: 4

== Use Case

In this blog post I'll show you how to deploy a simple _Quarkus_ application to _Azure_ using _GitHub Actions_, thanks to _NubesGen_.
To break it into more details, in this blog post you will learn:

* What is _GitHub Actions_?
* Use NubesGen to generate Terraform templates for a simple Quarkus application.
* Use NubesGen to generate _Git Actions_ so you can get CI/CD.
* How to deploy a Quarkus application to Azure.

=== Prerequisites

== What is GitHub Actions?

But first, let me introduce Terraform.
Terraform is...

== Generate a Simple Quarkus Application

First of all, let's generate a simple Quarkus application.
This application exposes a RestEndpoint that says "Hello NubesGen".
Nothing too fancy, but this allows us to focus on the deployment, not the code.

=== Bootstrap a Quarkus Application

Go to https://xxx[code.quarkus.io], specify your project name, group and artifact id, and select the Rest Easy extension.
Download the Zip file.
This is what you should have:

```
code
```

Now, to execute it, type `mvn quarkus:dev`.
Once Quarkus is up and ready, invoke the endpoint pointing at the URL ``.

=== Package the Application

We've just executed Quarkus in development mode.
What we need now is to package the application.
Quarkus has different ways of packaging an application:
as a Docker image, a native binary (thanks to GraalVM) or as an executable JAR.
Let's go for this option now, it's simple and portable.

To get a Uber-JAR of the application, execute the following command:

```
mvn package
```

To run the application is just a matter of executing:

```
mvn package
```

== Generate the NubesGen Artifacts

We have a simple application, with no database, no authentication, nothing, packaged in an executable Uber-JAR.
Let's ask NubesGen to generate the Terraform templates.

=== Main Terraform Template

=== Application Terraform Template

== Deploy to Azure

=== Execute the Terraform Templates

=== Check the Azure Console

== Conclusion

Terraform can be tricky.
Its language is simple, but because Terraforma has an extension mecanism, its ecosystem is huge.
You can find extension for Java, for AWS, for GCP... and for Azure.
Deploying to the cloud, even a simple application, can take you a few lines of code to write.


== References

